CREATE TABLE `#DB_APPS#_views` (
   `id` int(10) unsigned not null auto_increment,
   `title` varchar(255),
   `category` varchar(255),
   `header` varchar(255),
   `footer` varchar(255),
   `engine` varchar(255),
   `script` text,
   `style` text,
   `frmdata` text,
   `queries` text,
   `template` text,
   `blocked` enum('true','false') default 'false',
   `onmenu` enum('true','false') default 'true',
   `privilege` varchar(500) default '*',
   `privilege_model` varchar(2000) default '*',
   `weight` int(11) default '0',
   `hits` int(11) default '0',
   `site` varchar(55) default '*',
   `userid` varchar(255),
   `doc` date,
   `doe` date,
   PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
